### ISSUE TITLE
Add "Products collection" component

### ISSUE THREAD

**Issue by ozin7** [lembergsolutions/commerce_draft#129]
- [x] Add a new layout builder component
- [x] Administrator should be able to set collection heading
- [x] Administrator should be able to select products that will be displayed for this collection
- [x] Products should be rendered in teasers view mode

**Comment by serhii-morozov** [comment]
Sorry, but I can't found satisfied solution from the box in administration of Drupal. There is module 'Layout components' with already created components, but this module does not solve the task. I created component in module.
